package entities;

import entities.enums.SensorStatus;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Abstract sensor entity. Each sensor has a unique code,
 * belongs to a zone, has a status and a threshold range.
 * GPS collar sensors are a special subtype.
 */
public abstract class Sensor {
    private final String code;
    private SensorStatus status;
    private double minThreshold;
    private double maxThreshold;
    private final String zoneCode;
    private final List<SensorReading> readings;

    public Sensor(String code, String zoneCode, double minThreshold, double maxThreshold) {
        this.code = code;
        this.zoneCode = zoneCode;
        this.status = SensorStatus.ACTIVE;
        this.minThreshold = minThreshold;
        this.maxThreshold = maxThreshold;
        this.readings = new ArrayList<>();
    }

    public String getCode() { return code; }
    public SensorStatus getStatus() { return status; }
    public void setStatus(SensorStatus status) { this.status = status; }
    public double getMinThreshold() { return minThreshold; }
    public void setMinThreshold(double minThreshold) { this.minThreshold = minThreshold; }
    public double getMaxThreshold() { return maxThreshold; }
    public void setMaxThreshold(double maxThreshold) { this.maxThreshold = maxThreshold; }
    public String getZoneCode() { return zoneCode; }
    public List<SensorReading> getReadings() { return readings; }

    public void suspend() {
        this.status = SensorStatus.SUSPENDED;
    }

    public void reactivate() {
        this.status = SensorStatus.ACTIVE;
    }

    public boolean isActive() {
        return status == SensorStatus.ACTIVE;
    }

    /**
     * Records a new sensor reading. If active and value is out of range,
     * an alert should be generated by the use case layer.
     */
    public SensorReading recordReading(double value, String unit) {
        SensorReading reading = new SensorReading(this.code, value, unit, LocalDateTime.now());
        readings.add(reading);
        return reading;
    }

    /**
     * Checks whether the given value is outside the threshold range.
     */
    public boolean isOutOfRange(double value) {
        return value < minThreshold || value > maxThreshold;
    }

    public abstract String getType();
    public abstract String getUnit();

    @Override
    public String toString() {
        return "[" + code + "] " + getType() + " - " + status;
    }
}
